#!/usr/bin/env bash
# discover.sh — scan the current project and write
# .claude/rules/project-conventions.md.
#
# Detects: tech stack (manifests), build/test commands, naming conventions
# (from sampled source files), test setup, and rule sections from existing
# CLAUDE.md / AGENTS.md / README.md.
#
# Where it goes: `.claude/rules/`, not `docs/`. Claude Code discovers every
# `.md` under `.claude/rules/` recursively and loads a rule without a `paths:`
# frontmatter key at launch, with the same priority as `.claude/CLAUDE.md`
# (https://code.claude.com/docs/en/memory.md). The conventions are then already
# in context for every session instead of waiting for a skill to read them --
# which is the whole point of writing them down. Same reason the routing rule
# lives in `.claude/rules/ticket-flow-routing.md`. Because it is always loaded,
# the size target in SKILL.md (<= 250 lines) is a real budget, not a style note.
#
# Sandbox-safe: no network, read-only except for the output doc.
#
# Usage: discover.sh           (writes .claude/rules/project-conventions.md; refuses if it exists)
#        discover.sh --force   (overwrite without prompt)
#        discover.sh --stdout  (write to stdout instead of file; no prompt)
set -u

FORCE=0
TO_STDOUT=0
for arg in "$@"; do
  case "$arg" in
    --force)  FORCE=1 ;;
    --stdout) TO_STDOUT=1 ;;
    -h|--help) awk 'NR>1 && /^#/ { sub(/^# ?/, ""); print; next } NR>1 { exit }' "$0"; exit 0 ;;
    *) echo "ERROR: unknown arg '$arg'" >&2; exit 2 ;;
  esac
done

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
[[ -z "$ROOT" ]] && { echo "ERROR: not a git repo — discover requires git for sampling source files" >&2; exit 1; }
cd "$ROOT" || exit 1

OUT=".claude/rules/project-conventions.md"
LEGACY_OUT="docs/PROJECT-CONVENTIONS.md"
if (( ! TO_STDOUT )); then
  mkdir -p .claude/rules
  if [[ -f "$OUT" && $FORCE -eq 0 ]]; then
    echo "⚠ $OUT already exists. Re-run with --force to overwrite, or rename/move the existing file first." >&2
    exit 1
  fi
fi

emit() { if (( TO_STDOUT )); then printf '%s\n' "$*"; else printf '%s\n' "$*" >> "$OUT.tmp"; fi; }
header() { emit ""; emit "## $1"; emit ""; }

# --- Init output ---
if (( ! TO_STDOUT )); then
  : > "$OUT.tmp"
fi

PROJECT="$(basename "$ROOT")"
emit "# Project Conventions — $PROJECT"
emit ""
emit "_Generated by \`/ticket-flow:discover\` on $(date -u +%Y-%m-%d). Re-run when the stack changes significantly._"
emit ""
emit "_Project rule: Claude Code loads this file into every session in this repository. Keep it short — edit it by hand where the scan got something wrong._"

# --- 1. Tech Stack ---
header "Tech Stack"
declare -a STACK
[[ -f package.json ]]      && STACK+=("Node.js / JavaScript / TypeScript (\`package.json\`)")
[[ -f Cargo.toml ]]        && STACK+=("Rust (\`Cargo.toml\`)")
[[ -f pyproject.toml ]]    && STACK+=("Python (\`pyproject.toml\`)")
[[ -f requirements.txt && ! -f pyproject.toml ]] && STACK+=("Python (\`requirements.txt\`)")
[[ -f go.mod ]]            && STACK+=("Go (\`go.mod\`)")
[[ -f Package.swift ]]     && STACK+=("Swift / SwiftPM (\`Package.swift\`)")
[[ -f Gemfile ]]           && STACK+=("Ruby (\`Gemfile\`)")
[[ -f composer.json ]]     && STACK+=("PHP (\`composer.json\`)")
[[ -f pom.xml ]]           && STACK+=("Java / Maven (\`pom.xml\`)")
[[ -f build.gradle || -f build.gradle.kts ]] && STACK+=("JVM / Gradle (\`build.gradle\`)")
compgen -G "*.csproj" > /dev/null 2>&1 && STACK+=(".NET / C# (\`*.csproj\`)")
[[ -f mix.exs ]]           && STACK+=("Elixir (\`mix.exs\`)")
[[ -f Makefile ]]          && STACK+=("Has Makefile")
[[ -f Dockerfile ]]        && STACK+=("Containerized (\`Dockerfile\`)")
SHELL_COUNT="$(git ls-files '*.sh' 2>/dev/null | wc -l | tr -d ' ')"
(( SHELL_COUNT > 0 )) && STACK+=("Shell scripts: $SHELL_COUNT files")

if (( ${#STACK[@]} == 0 )); then
  emit "_No standard manifest files detected._"
else
  for s in "${STACK[@]}"; do emit "- $s"; done
fi

# Versions from common manifests
declare -a VERSIONS
if [[ -f package.json ]] && command -v jq >/dev/null 2>&1; then
  V="$(jq -r '.engines.node // empty' package.json 2>/dev/null)"
  [[ -n "$V" ]] && VERSIONS+=("Node engines: $V")
  V="$(jq -r '.packageManager // empty' package.json 2>/dev/null)"
  [[ -n "$V" ]] && VERSIONS+=("Package manager: $V")
fi
if [[ -f Cargo.toml ]]; then
  V="$(grep -E '^edition' Cargo.toml | head -1 | sed 's/.*= *//; s/"//g')"
  [[ -n "$V" ]] && VERSIONS+=("Rust edition: $V")
fi
if [[ -f Package.swift ]]; then
  V="$(grep -E 'swift-tools-version' Package.swift | head -1 | sed 's/.*://; s/[^0-9.]//g')"
  [[ -n "$V" ]] && VERSIONS+=("swift-tools-version: $V")
fi
if [[ -f pyproject.toml ]]; then
  V="$(grep -E '^python ?=' pyproject.toml | head -1 | sed 's/.*= *//; s/"//g')"
  [[ -n "$V" ]] && VERSIONS+=("Python: $V")
fi
if (( ${#VERSIONS[@]} > 0 )); then
  emit ""
  for v in "${VERSIONS[@]}"; do emit "- $v"; done
fi

# --- 2. Build / Test / Lint commands ---
header "Build / Test / Lint Commands"
declare -a CMDS
if [[ -f package.json ]] && command -v jq >/dev/null 2>&1; then
  while IFS= read -r line; do
    [[ -n "$line" ]] && CMDS+=("\`npm run $line\` (or \`pnpm $line\` / \`yarn $line\`)")
  done < <(jq -r '.scripts // {} | keys[]' package.json 2>/dev/null)
fi
[[ -f Cargo.toml ]]    && CMDS+=("\`cargo build\` / \`cargo test\` / \`cargo clippy\` / \`cargo fmt\`")
[[ -f go.mod ]]        && CMDS+=("\`go build ./...\` / \`go test ./...\` / \`go vet ./...\`")
[[ -f Package.swift ]] && CMDS+=("\`swift build\` / \`swift test\`")
[[ -f Gemfile ]]       && CMDS+=("\`bundle exec rspec\` / \`bundle exec rake\`")
[[ -f pyproject.toml ]] && CMDS+=("\`pytest\` (or framework-specific runner)")
[[ -f Makefile ]] && {
  TARGETS="$(grep -E '^[a-zA-Z0-9_-]+:' Makefile | sed 's/:.*//' | tr '\n' ' ')"
  [[ -n "$TARGETS" ]] && CMDS+=("Makefile targets: $TARGETS")
}
if (( ${#CMDS[@]} == 0 )); then
  emit "_No build/test commands detected. Document them here manually if applicable._"
else
  for c in "${CMDS[@]}"; do emit "- $c"; done
fi

# --- 3. Source file conventions ---
header "Source File Naming & Layout"
SAMPLE_EXTS="$(git ls-files 2>/dev/null | sed -n 's/.*\.\([A-Za-z0-9]\{1,5\}\)$/\1/p' | sort | uniq -c | sort -rn | head -10)"
if [[ -n "$SAMPLE_EXTS" ]]; then
  emit "Top file extensions in the repo:"
  emit '```'
  emit "$SAMPLE_EXTS"
  emit '```'
fi

# Sample 20 source files and infer naming style for each top extension.
emit ""
emit "Naming patterns by extension (sampled):"
TOP_EXTS="$(echo "$SAMPLE_EXTS" | awk '{print $2}' | head -5)"
for EXT in $TOP_EXTS; do
  case "$EXT" in
    md|txt|json|yml|yaml|lock|toml|gitignore|gitattributes) continue ;;
  esac
  SAMPLES="$(git ls-files "*.$EXT" 2>/dev/null | shuf 2>/dev/null | head -10 || git ls-files "*.$EXT" 2>/dev/null | head -10)"
  [[ -z "$SAMPLES" ]] && continue
  emit ""
  emit "**.$EXT** — sample basenames:"
  emit '```'
  echo "$SAMPLES" | awk -F/ '{print $NF}'  | (if (( TO_STDOUT )); then cat; else cat >> "$OUT.tmp"; fi)
  emit '```'
done

# --- 4. Testing setup ---
header "Testing Setup"
declare -a TESTING
[[ -d tests ]]      && TESTING+=("\`tests/\` directory present")
[[ -d test ]]       && TESTING+=("\`test/\` directory present")
[[ -d Tests ]]      && TESTING+=("\`Tests/\` directory present (Apple convention)")
[[ -d __tests__ ]]  && TESTING+=("\`__tests__/\` directory present (Jest convention)")
[[ -d spec ]]       && TESTING+=("\`spec/\` directory present (RSpec convention)")
# `grep -c` prints 0 and exits 1 when nothing matches, so a `|| echo 0` here
# appended a second line and made the arithmetic below a syntax error.
TEST_FILE_COUNT="$(git ls-files 2>/dev/null | grep -cE '(^|/)(test|tests?|spec)/.+|.+(_test|_spec|Tests|Test)\.[A-Za-z0-9]+$' 2>/dev/null)"
[[ "$TEST_FILE_COUNT" =~ ^[0-9]+$ ]] || TEST_FILE_COUNT=0
(( TEST_FILE_COUNT > 0 )) && TESTING+=("Test-shaped files: $TEST_FILE_COUNT")
if (( ${#TESTING[@]} == 0 )); then
  emit "_No tests detected. Either the project has none, or they live somewhere unusual._"
else
  for t in "${TESTING[@]}"; do emit "- $t"; done
fi

# --- 5. Rule/convention sections from existing docs ---
header "Existing Rules & Conventions (from CLAUDE.md / AGENTS.md / README.md)"
declare -a DOCS_FOUND
[[ -f CLAUDE.md ]] && DOCS_FOUND+=("CLAUDE.md")
[[ -f AGENTS.md ]] && DOCS_FOUND+=("AGENTS.md")
[[ -f README.md ]] && DOCS_FOUND+=("README.md")

if (( ${#DOCS_FOUND[@]} == 0 )); then
  emit "_No CLAUDE.md / AGENTS.md / README.md present. Consider creating one._"
else
  for d in "${DOCS_FOUND[@]}"; do
    LINES="$(wc -l < "$d" | tr -d ' ')"
    emit "- **$d** — $LINES lines. Sections: $(grep -E '^## ' "$d" | sed 's/^## //' | tr '\n' '·' | sed 's/·$//; s/·/ · /g')"
  done
fi

# --- 6. Anti-patterns / "DO NOT" rules ---
header "Anti-Patterns (DO NOT lines from existing docs)"
emit "_Scraped by keyword — candidates, not verified rules. Delete what is not one; this file is loaded into every session._"
emit ""
declare -a DONTS
for d in CLAUDE.md AGENTS.md README.md; do
  [[ -f "$d" ]] || continue
  while IFS= read -r line; do
    [[ -n "$line" ]] && DONTS+=("[$d] $line")
  # Table rows, headings and quotes are not rules — a matched markdown table
  # row used to land here verbatim, mangling the output and adding a
  # "prohibition" that was really a credits entry. Over-long lines are prose,
  # not rules, so they go too.
  done < <(grep -E -i '(do not|don.?t|never|avoid|forbidden|prohibited)' "$d" 2>/dev/null \
             | grep -vE '^[[:space:]]*([|#>]|!\[)' \
             | sed 's/^[[:space:]-]*//' \
             | awk 'length($0) > 0 && length($0) <= 200' \
             | head -10)
done
if (( ${#DONTS[@]} == 0 )); then
  emit "_No explicit anti-pattern rules found._"
else
  for d in "${DONTS[@]}"; do emit "- $d"; done
fi

# --- Finalize ---
emit ""
emit "---"
emit ""
emit "_If something below is wrong, edit this file directly — \`/ticket-flow:discover\` will refuse to overwrite without \`--force\`._"

if (( ! TO_STDOUT )); then
  mv "$OUT.tmp" "$OUT"
  LINES="$(wc -l < "$OUT" | tr -d ' ')"
  echo "✓ Wrote $OUT ($LINES lines)"
  if (( LINES > 250 )); then
    echo "  note: over the 250-line budget — this file is loaded into every session, so trim it."
  fi
  if ! git ls-files --error-unmatch "$OUT" >/dev/null 2>&1; then
    echo "  note: not tracked by git yet — a worktree checkout carries only tracked"
    echo "        files, so dispatched agents would not see it. \`git add $OUT\`"
  fi
  if [[ -f "$LEGACY_OUT" ]]; then
    echo "  note: $LEGACY_OUT is the old location and is no longer read by any skill."
    echo "        Merge anything you still want into $OUT, then delete it."
  fi
fi
